const Projects = [
    {
        Id: '1',
        pImg:'/images/projects/img-1.jpg',
        video:'/videos/video-1.mp4',
        slug:'Water-Line-Repair',
        subTitle:'Plumbing',
        title: 'Water Line Repair',
        description:'High‑precision leak detection, code‑safe pipe repairs, and pressure restored — fast, clean, and guaranteed.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '2',
        pImg:'/images/projects/img-3.jpg',
        slug:'Basement-Plumbing',
        subTitle:'Plumbing',
        title: 'Basement Plumbing',
        description:'Dry, dependable basements — sump pumps, backflow prevention, and moisture‑safe rough‑ins done right.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    // {
    //     Id: '3',
    //     pImg:'/images/projects/img-2.jpg',
    //     slug:'Remodeling-Service',
    //     subTitle:'Plumbing',
    //     title: 'Remodeling Service',
    //     description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
    //     spImg1:'/images/project-single/2.jpg',
    //     spImg2:'/images/project-single/3.jpg',
    // },
    {
        Id: '4',
        pImg:'/images/projects/img-7.jpg',
        video:'/videos/video-2.mp4',
        slug:'Water-Line-Repairs',
        subTitle:'Plumbing',
        title: 'Water Line Repair',
        description:'Goodbye low pressure and hidden leaks — durable replacements with neat finishes that last.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '5',
        pImg:'/images/projects/img-8.jpg',
        video:'/videos/video-4.mp4',
        slug:'Kitchen-Plumbing',
        subTitle:'Plumbing',
        title: 'Kitchen Plumbing',
        description:'Effortless flow in the heart of your home — sinks, faucets, and disposals installed to perfection.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '6',
        pImg:'/images/gasslinerepaer.jpg',
        slug:'Gas-Line-Services',
        subTitle:'Plumbing',
        title: 'Gas Line Services',
        description:'Safe, code-compliant gas line installation and repair for your home appliances and heating systems.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '7',
        pImg:'/images/projects/img-6.jpg',
        video:'/videos/video-3.mp4',
        slug:'Accessible Clean Out',
        subTitle:'Plumbing',
        title: 'Accessible Clean Out',
        description:'Future‑proof service access — easy cleanouts that make maintenance quicker, safer, and cheaper.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    // {
    //     Id: '8',
    //     pImg:'/images/projects/img-10.jpg',
    //     slug:'Basement-Plumber',
    //     subTitle:'Plumbing',
    //     title: 'Basement Plumbing',
    //     description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
    //     spImg1:'/images/project-single/2.jpg',
    //     spImg2:'/images/project-single/3.jpg',
    // },
    // {
    //     Id: '9',
    //     pImg:'/images/projects/img-11.jpg',
    //     slug:'Remodeling-Services',
    //     subTitle:'Plumbing',
    //     title: 'Remodeling Service',
    //     description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
    //     spImg1:'/images/project-single/2.jpg',
    //     spImg2:'/images/project-single/3.jpg',
    // },
]
export default Projects;
