const Services = [
    // {
    //     Id: '1',
    //     sImg:'/images/service/1.jpg',
    //     sIcon:'/images/icon/kitchen-utensils.png',
    //     slug:'Kitchen-Plumbing',
    //     sTitle: 'Kitchen Plumbing',
    //     description:'Electronic typesetting rema essentially unchanged was popularised.',
    //     ssImg1:'/images/service-single/2.jpg',
    //     ssImg2:'/images/service-single/3.jpg',
    // },
    // {
    //     Id: '2',
    //     sImg:'/images/service/2.jpg',
    //     sIcon:'/images/icon/gas-stove.png',
    //     slug:'Gas-Line-Services',
    //     sTitle: 'Gas Line Services',
    //     description:'Electronic typesetting rema essentially unchanged was popularised.',
    //     ssImg1:'/images/service-single/2.jpg',
    //     ssImg2:'/images/service-single/3.jpg',
    // },
    // {
    //     Id: '3',
    //     sImg:'/images/service/3.jpg',
    //     sIcon:'/images/icon/water-tap.png',
    //     slug:'Water-Line-Repair',
    //     sTitle: 'Water Line Repair',
    //     description:'Electronic typesetting rema essentially unchanged was popularised.',
    //     ssImg1:'/images/service-single/2.jpg',
    //     ssImg2:'/images/service-single/3.jpg',
    // },

    {
        Id: '1',
        sImg:'/images/service/1.jpg',
        sIcon:'/images/icon/express-delivery.svg',
        slug:'emergency-plumbing',
        sTitle: 'Emergency Plumbing',
        description:'24/7 rapid response for urgent leaks, backups, and burst pipes.',
        overview: 'When water is where it shouldn’t be, speed matters. Our dispatch team connects you with a certified plumber right away — day or night. We diagnose fast, stop active leaks, and implement sturdy fixes with transparent pricing before work begins.',
        keyPoints: [
            'Live 24/7 dispatch with same-day arrival',
            'On‑site diagnostics and immediate stabilization',
            'Upfront pricing with repair options explained',
            'Fully stocked trucks to solve most issues on the spot',
            'Clean, respectful work — we protect floors and surfaces'
        ],
        ssImg1:'/images/service-single/1.jpg',
        ssImg2:'/images/service-single/2.jpg',
    },
    {
        Id: '2',
        sImg:'/images/service/2.jpg',
        sIcon:'/images/icon/water-tap.png',
        slug:'drain-cleaning',
        sTitle: 'Drain Cleaning — $69.99',
        description:'Fast, professional drain clearing at a straightforward flat rate.',
        overview: 'Slow or backed‑up drains are frustrating and can lead to bigger plumbing problems. We clear the clog quickly, verify flow, and recommend maintenance tips to keep lines clean. For heavy buildup, we can camera inspect and jet for a long‑term solution.',
        keyPoints: [
            'Flat‑rate residential drain clearing — no surprises',
            'Power augering to remove common clogs',
            'Optional camera inspection to locate trouble spots',
            'Hydro jetting available for grease and scale',
            'Warranty‑backed work and clean job sites'
        ],
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '3',
        sImg:'/images/service/3.jpg',
        sIcon:'/images/icon/water-tap.png',
        slug:'water-heater-service',
        sTitle: 'Water Heater Repair & Install',
        description:'Reliable repairs and energy‑efficient replacements—tank and tankless.',
        overview: 'From no‑hot‑water emergencies to energy‑efficient upgrades, we service all major brands — tank and tankless. We troubleshoot quickly, explain repair vs replace options, and install to code with proper venting, gas, and recirculation when needed.',
        keyPoints: [
            'Same‑day repair and replacement for most models',
            'Tank and tankless expertise — gas and electric',
            'Code‑compliant installs with permits handled',
            'Removal and disposal of old units',
            'Manufacturer warranties honored and registered'
        ],
        ssImg1:'/images/service-single/1.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '4',
        sImg:'/images/service/4.jpg',
        sIcon:'/images/icon/pipe.png',
        slug:'leak-detection-repair',
        sTitle: 'Leak Detection & Repair',
        description:'Pinpoint leaks and fix them fast to prevent water damage.',
        overview: 'Hidden leaks waste water and can damage walls, floors, and foundations. We use acoustic and thermal tools to locate the source precisely, then repair with the least invasive method possible — protecting finishes and preventing repeat issues.',
        keyPoints: [
            'Non‑invasive detection to pinpoint leak sources',
            'Targeted repairs that minimize wall/floor cuts',
            'Pressure testing to confirm repairs',
            'Slab leak specialists available',
            'Moisture mapping and cleanup recommendations'
        ],
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '5',
        sImg:'/images/service/5.jpg',
        sIcon:'/images/icon/pipe.png',
        slug:'sewer-trenchless',
        sTitle: 'Sewer & Trenchless Solutions',
        description:'Non‑invasive repairs, replacements, and cleanouts for lasting flow.',
        overview: 'For failing or root‑intruded sewer lines, trenchless methods can restore flow without tearing up landscaping. We camera inspect, recommend the right approach — lining, pipe bursting, or spot repair — and verify results before we leave.',
        keyPoints: [
            'Camera inspection with recorded footage',
            'CIPP lining and pipe bursting options',
            'Minimal disruption to concrete and landscaping',
            'New cleanouts installed where needed',
            'Post‑repair verification and warranty'
        ],
        ssImg1:'/images/service-single/1.jpg',
        ssImg2:'/images/service-single/2.jpg',
    },
    {
        Id: '6',
        sImg:'/images/service/6.jpg',
        sIcon:'/images/icon/prototype.svg',
        slug:'hydro-jetting',
        sTitle: 'Hydro Jetting Service',
        description:'High‑pressure cleaning to clear heavy buildup in drains and sewers.',
        overview: 'Jetting uses high‑pressure water to scour the inside of pipes — ideal for grease, scale, and roots. We pair jetting with camera inspection to confirm a thorough clean and help prevent future clogs.',
        keyPoints: [
            'Commercial‑grade jetting up to 4,000 PSI',
            'Descaling and grease removal for long‑term flow',
            'Pre/post camera inspection to validate results',
            'Suitable for residential and commercial lines',
            'Maintenance plans available'
        ],
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '7',
        sImg:'/images/service/7.jpg',
        sIcon:'/images/icon/sink.png',
        slug:'slab-leak-repair',
        sTitle: 'Slab Leak Repair',
        description:'Expert detection and repair to protect your foundation and home.',
        overview: 'Slab leaks require precision and care. We locate the leak, discuss repair paths — direct access or reroute — and restore service while protecting your home’s structure and finishes.',
        keyPoints: [
            'Pressure testing and isolation to find leak',
            'Direct repair or reroute options clearly explained',
            'Experienced crews to minimize dust and noise',
            'Drywall patching and clean site practices',
            'Permits and code compliance handled'
        ],
        ssImg1:'/images/service-single/1.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '8',
        sImg:'/images/service/4.jpg',
        sIcon:'/images/icon/pipe.png',
        slug:'accessible-clean-out',
        sTitle: 'Accessible Clean Out',
        description:'Install or upgrade accessible clean outs for easier maintenance.',
        overview: 'Proper cleanouts make future maintenance faster and less invasive. We install new cleanouts or relocate existing ones to accessible locations, ensuring code compliance and easier service access.',
        keyPoints: [
            'Evaluate best location for accessibility',
            'Install new cleanout to code',
            'Optional backwater valve recommendations',
            'Labeling and cap protection included',
            'Improves future service time and cost'
        ],
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '9',
        sImg:'/images/service/1.jpg',
        sIcon:'/images/icon/water-tap.png',
        slug:'burst-pipe-repair',
        sTitle: 'Burst Pipe Repair',
        description:'Emergency pipe repairs to stop water damage fast.',
        overview: 'We quickly locate the break, shut off water, and perform durable repairs or replacements. We protect your property during service and advise on prevention.',
        keyPoints: [
            'Rapid response and water shut‑off',
            'Targeted repair or section replacement',
            'Moisture mitigation recommendations',
            'Pressure testing to verify integrity',
            'Clean, respectful work inside homes'
        ],
        ssImg1:'/images/service-single/1.jpg',
        ssImg2:'/images/service-single/2.jpg',
    },
    {
        Id: '10',
        sImg:'/images/service/2.jpg',
        sIcon:'/images/icon/sink.png',
        slug:'toilet-repair-install',
        sTitle: 'Toilet Repair & Install',
        description:'Fix leaks, clogs, and installs for all models.',
        overview: 'From running toilets to complete replacements, we service all brands and install new units to code, including low‑flow and comfort‑height options.',
        keyPoints: [
            'Flapper, fill valve, and wax ring fixes',
            'Clog clearing and re‑seating',
            'New installs with haul‑away',
            'Seal testing to prevent future leaks',
            'ADA and water‑saving options'
        ],
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '11',
        sImg:'/images/service/3.jpg',
        sIcon:'/images/icon/water-tap.png',
        slug:'faucet-repair-install',
        sTitle: 'Faucet Repair & Install',
        description:'Drip fixes, cartridge swaps, and stylish upgrades.',
        overview: 'We repair leaks and low pressure issues, and install new faucets for kitchens, baths, and laundry — neatly and to manufacturer specs.',
        keyPoints: [
            'Cartridge and aerator replacements',
            'Supply line and shut‑off valve updates',
            'Finish‑safe work to protect sinks and counters',
            'Kitchen, bath, and utility faucets',
            'Optional touch and pull‑down models'
        ],
        ssImg1:'/images/service-single/1.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '12',
        sImg:'/images/service/4.jpg',
        sIcon:'/images/icon/prototype.svg',
        slug:'garbage-disposal',
        sTitle: 'Garbage Disposal Service',
        description:'Repair, replace, and clear jammed disposals.',
        overview: 'We service all major disposal brands, clearing jams and replacing worn units. Installs include proper wiring checks and leak tests.',
        keyPoints: [
            'Jam clearing and reset diagnostics',
            'Noise and vibration fixes',
            'New installs with flange and putty set',
            'Electrical and leak safety checks',
            'Warranty options available'
        ],
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/1.jpg',
    },
    {
        Id: '13',
        sImg:'/images/service/5.jpg',
        sIcon:'/images/icon/pipe.png',
        slug:'repiping',
        sTitle: 'Whole‑Home Repiping',
        description:'Replace aging lines with modern, code‑compliant piping.',
        overview: 'For frequent leaks and poor pressure, repiping restores reliability. We plan routes, protect finishes, and complete work efficiently and to code.',
        keyPoints: [
            'Copper, PEX, and hybrid options',
            'Pressure balancing and isolation valves',
            'Drywall patching coordinated',
            'Permit handling and inspections',
            'Clear timelines and daily cleanup'
        ],
        ssImg1:'/images/service-single/3.jpg',
        ssImg2:'/images/service-single/2.jpg',
    },
    {
        Id: '14',
        sImg:'/images/service/6.jpg',
        sIcon:'/images/icon/water-tap.png',
        slug:'main-water-line',
        sTitle: 'Main Water Line Repair/Replace',
        description:'Repair breaks and upgrade aging service lines.',
        overview: 'We locate and repair yard and street‑side line failures, and replace undersized or corroded service lines for strong, reliable flow.',
        keyPoints: [
            'Leak location and isolation',
            'Trenchless replacement options',
            'Pressure regulation via PRV setup',
            'Code‑compliant materials and depth',
            'Final pressure and flow testing'
        ],
        ssImg1:'/images/service-single/1.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '15',
        sImg:'/images/service/2.jpg',
        sIcon:'/images/icon/pipe.png',
        slug:'sewer-line-repair',
        sTitle: 'Sewer Line Repair & Replace',
        description:'Camera inspections and trenchless solutions to restore flow.',
        overview: 'We diagnose root intrusion and breaks with camera inspections, then perform spot repairs or full replacements using trenchless techniques where possible.',
        keyPoints: [
            'Recorded camera inspections',
            'Spot repair or full replacement',
            'CIPP lining and pipe bursting',
            'Cleanouts and backwater valves',
            'Warranty‑backed solutions'
        ],
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/1.jpg',
    },
    {
        Id: '16',
        sImg:'/images/service/3.jpg',
        sIcon:'/images/icon/prototype.svg',
        slug:'camera-inspection',
        sTitle: 'Camera Inspection',
        description:'Pinpoint clogs and breaks with HD video inspection.',
        overview: 'We map your drain and sewer lines to locate problems and provide clear recommendations with video evidence for insurance or future reference.',
        keyPoints: [
            'HD footage and location mapping',
            'Pre/post service validation',
            'Ideal with jetting and sewer repairs',
            'Digital reports available',
            'Helps avoid repeat issues'
        ],
        ssImg1:'/images/service-single/3.jpg',
        ssImg2:'/images/service-single/1.jpg',
    },
    {
        Id: '17',
        sImg:'/images/service/4.jpg',
        sIcon:'/images/icon/water-tap.png',
        slug:'backflow-prevention',
        sTitle: 'Backflow Prevention & Testing',
        description:'Install, repair, and test backflow devices for safety.',
        overview: 'Protect your water supply with certified installation, repair, and annual testing of backflow prevention assemblies for residential and commercial systems.',
        keyPoints: [
            'Certified testing and documentation',
            'Repairs on all major devices',
            'New installs to code',
            'Irrigation and commercial systems',
            'Annual reminders available'
        ],
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '18',
        sImg:'/images/service/5.jpg',
        sIcon:'/images/icon/water-tap.png',
        slug:'water-softener',
        sTitle: 'Water Softener Install',
        description:'Softer water for longer‑lasting fixtures and appliances.',
        overview: 'We size and install softeners to reduce scale, protect plumbing, and improve feel. Options include whole‑home systems with bypass and drain setups.',
        keyPoints: [
            'System sizing and placement',
            'Bypass valve and drain connections',
            'Media selection and setup',
            'Code‑compliant installs',
            'Maintenance guidance'
        ],
        ssImg1:'/images/service-single/1.jpg',
        ssImg2:'/images/service-single/2.jpg',
    },
    {
        Id: '19',
        sImg:'/images/service/6.jpg',
        sIcon:'/images/icon/water-tap.png',
        slug:'reverse-osmosis',
        sTitle: 'Reverse Osmosis (RO) Systems',
        description:'Cleaner drinking water from under‑sink RO systems.',
        overview: 'We install and maintain RO systems for great‑tasting water. Installs include dedicated faucet, tank placement, and leak checks.',
        keyPoints: [
            'System selection and install',
            'Dedicated faucet setup',
            'Filter changes and maintenance',
            'Leak and pressure checks',
            'Options for fridge line connection'
        ],
        ssImg1:'/images/service-single/3.jpg',
        ssImg2:'/images/service-single/2.jpg',
    },
    {
        Id: '20',
        sImg:'/images/service/2.jpg',
        sIcon:'/images/icon/water-tap.png',
        slug:'whole-home-filtration',
        sTitle: 'Whole‑Home Filtration',
        description:'Improve taste and reduce contaminants for the whole home.',
        overview: 'We design and install point‑of‑entry filtration systems tailored to your water quality, with media changes and service plans available.',
        keyPoints: [
            'Water quality assessment',
            'System sizing and plumbing',
            'Media selection and changes',
            'Bypass and drain setups',
            'Service and maintenance plans'
        ],
        ssImg1:'/images/service-single/1.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '21',
        sImg:'/images/service/3.jpg',
        sIcon:'/images/icon/prototype.svg',
        slug:'sump-pump',
        sTitle: 'Sump Pump Install & Repair',
        description:'Keep basements and crawl spaces dry and protected.',
        overview: 'We install and service sump and ejector pumps, including basins, check valves, and battery backups for reliable performance.',
        keyPoints: [
            'Pump sizing and basin install',
            'Check valve and discharge piping',
            'Battery backup options',
            'Maintenance and testing',
            'Emergency replacements'
        ],
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/1.jpg',
    },
    {
        Id: '22',
        sImg:'/images/service/4.jpg',
        sIcon:'/images/icon/gas-stove.png',
        slug:'gas-line-service',
        sTitle: 'Gas Line Repair & Install',
        description:'Safe gas piping for appliances and outdoor kitchens.',
        overview: 'Certified gas line service including leak repair, new appliance connections, and outdoor kitchen or fire pit setups — tested and permitted.',
        keyPoints: [
            'Leak detection and repair',
            'New appliance hookups',
            'Outdoor kitchen/fire pit lines',
            'Pressure testing and permits',
            'Code‑compliant materials'
        ],
        ssImg1:'/images/service-single/3.jpg',
        ssImg2:'/images/service-single/2.jpg',
    },
    {
        Id: '23',
        sImg:'/images/service/5.jpg',
        sIcon:'/images/icon/sink.png',
        slug:'pressure-regulator-prv',
        sTitle: 'Pressure Regulator (PRV) Replace',
        description:'Protect lines and fixtures with proper water pressure.',
        overview: 'We test and replace failing PRVs to stabilize household water pressure, extending the life of appliances and plumbing fixtures.',
        keyPoints: [
            'Pressure testing at fixtures',
            'Code‑compliant PRV installs',
            'Shut‑off valve checks',
            'Leak and performance testing',
            'Warranty on parts and labor'
        ],
        ssImg1:'/images/service-single/1.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '24',
        sImg:'/images/service/6.jpg',
        sIcon:'/images/icon/water-tap.png',
        slug:'valve-replacement',
        sTitle: 'Valve Replacement',
        description:'Update failing shut‑offs and fixture valves.',
        overview: 'We replace stuck or leaking valves throughout the home to improve safety and serviceability, including main shut‑offs and fixture stops.',
        keyPoints: [
            'Fixture stop and angle stop updates',
            'Main shut‑off replacements',
            'Supply line refreshes',
            'Leak checks across fixtures',
            'Neat, finish‑safe work'
        ],
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/1.jpg',
    },
    // {
    //     Id: '6',
    //     sImg:'/images/service/6.jpg',
    //     sIcon:'/images/icon/remodeling.png',
    //     slug:'Remodeling-Service',
    //     sTitle: 'Remodeling Service',
    //     description:'Electronic typesetting rema essentially unchanged was popularised.',
    //     ssImg1:'/images/service-single/2.jpg',
    //     ssImg2:'/images/service-single/3.jpg',
    // },
   
]
export default Services;