const Services = [
    // {
    //     Id: '1',
    //     sImg:'/images/service/1.jpg',
    //     sIcon:'/images/icon/kitchen-utensils.png',
    //     slug:'Kitchen-Plumbing',
    //     sTitle: 'Kitchen Plumbing',
    //     description:'Electronic typesetting rema essentially unchanged was popularised.',
    //     ssImg1:'/images/service-single/2.jpg',
    //     ssImg2:'/images/service-single/3.jpg',
    // },
    // {
    //     Id: '2',
    //     sImg:'/images/service/2.jpg',
    //     sIcon:'/images/icon/gas-stove.png',
    //     slug:'Gas-Line-Services',
    //     sTitle: 'Gas Line Services',
    //     description:'Electronic typesetting rema essentially unchanged was popularised.',
    //     ssImg1:'/images/service-single/2.jpg',
    //     ssImg2:'/images/service-single/3.jpg',
    // },
    // {
    //     Id: '3',
    //     sImg:'/images/service/3.jpg',
    //     sIcon:'/images/icon/water-tap.png',
    //     slug:'Water-Line-Repair',
    //     sTitle: 'Water Line Repair',
    //     description:'Electronic typesetting rema essentially unchanged was popularised.',
    //     ssImg1:'/images/service-single/2.jpg',
    //     ssImg2:'/images/service-single/3.jpg',
    // },

    {
        Id: '1',
        sImg:'/images/service/1.jpg',
        sIcon:'/images/icon/express-delivery.svg',
        slug:'emergency-plumbing',
        sTitle: 'Emergency Plumbing',
        description:'24/7 rapid response for urgent leaks, backups, and burst pipes.',
        overview: 'When water is where it shouldn’t be, speed matters. Our dispatch team connects you with a certified plumber right away — day or night. We diagnose fast, stop active leaks, and implement sturdy fixes with transparent pricing before work begins.',
        keyPoints: [
            'Live 24/7 dispatch with same-day arrival',
            'On‑site diagnostics and immediate stabilization',
            'Upfront pricing with repair options explained',
            'Fully stocked trucks to solve most issues on the spot',
            'Clean, respectful work — we protect floors and surfaces'
        ],
        ssImg1:'/images/service-single/1.jpg',
        ssImg2:'/images/service-single/2.jpg',
    },
    {
        Id: '2',
        sImg:'/images/service/2.jpg',
        sIcon:'/images/icon/water-tap.png',
        slug:'drain-cleaning',
        sTitle: 'Drain Cleaning — $69.99',
        description:'Fast, professional drain clearing at a straightforward flat rate.',
        overview: 'Slow or backed‑up drains are frustrating and can lead to bigger plumbing problems. We clear the clog quickly, verify flow, and recommend maintenance tips to keep lines clean. For heavy buildup, we can camera inspect and jet for a long‑term solution.',
        keyPoints: [
            'Flat‑rate residential drain clearing — no surprises',
            'Power augering to remove common clogs',
            'Optional camera inspection to locate trouble spots',
            'Hydro jetting available for grease and scale',
            'Warranty‑backed work and clean job sites'
        ],
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '3',
        sImg:'/images/service/3.jpg',
        sIcon:'/images/icon/water-tap.png',
        slug:'water-heater-service',
        sTitle: 'Water Heater Repair & Install',
        description:'Reliable repairs and energy‑efficient replacements—tank and tankless.',
        overview: 'From no‑hot‑water emergencies to energy‑efficient upgrades, we service all major brands — tank and tankless. We troubleshoot quickly, explain repair vs replace options, and install to code with proper venting, gas, and recirculation when needed.',
        keyPoints: [
            'Same‑day repair and replacement for most models',
            'Tank and tankless expertise — gas and electric',
            'Code‑compliant installs with permits handled',
            'Removal and disposal of old units',
            'Manufacturer warranties honored and registered'
        ],
        ssImg1:'/images/service-single/1.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '4',
        sImg:'/images/service/4.jpg',
        sIcon:'/images/icon/pipe.png',
        slug:'leak-detection-repair',
        sTitle: 'Leak Detection & Repair',
        description:'Pinpoint leaks and fix them fast to prevent water damage.',
        overview: 'Hidden leaks waste water and can damage walls, floors, and foundations. We use acoustic and thermal tools to locate the source precisely, then repair with the least invasive method possible — protecting finishes and preventing repeat issues.',
        keyPoints: [
            'Non‑invasive detection to pinpoint leak sources',
            'Targeted repairs that minimize wall/floor cuts',
            'Pressure testing to confirm repairs',
            'Slab leak specialists available',
            'Moisture mapping and cleanup recommendations'
        ],
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '5',
        sImg:'/images/service/5.jpg',
        sIcon:'/images/icon/pipe.png',
        slug:'sewer-trenchless',
        sTitle: 'Sewer & Trenchless Solutions',
        description:'Non‑invasive repairs, replacements, and cleanouts for lasting flow.',
        overview: 'For failing or root‑intruded sewer lines, trenchless methods can restore flow without tearing up landscaping. We camera inspect, recommend the right approach — lining, pipe bursting, or spot repair — and verify results before we leave.',
        keyPoints: [
            'Camera inspection with recorded footage',
            'CIPP lining and pipe bursting options',
            'Minimal disruption to concrete and landscaping',
            'New cleanouts installed where needed',
            'Post‑repair verification and warranty'
        ],
        ssImg1:'/images/service-single/1.jpg',
        ssImg2:'/images/service-single/2.jpg',
    },
    {
        Id: '6',
        sImg:'/images/service/6.jpg',
        sIcon:'/images/icon/prototype.svg',
        slug:'hydro-jetting',
        sTitle: 'Hydro Jetting Service',
        description:'High‑pressure cleaning to clear heavy buildup in drains and sewers.',
        overview: 'Jetting uses high‑pressure water to scour the inside of pipes — ideal for grease, scale, and roots. We pair jetting with camera inspection to confirm a thorough clean and help prevent future clogs.',
        keyPoints: [
            'Commercial‑grade jetting up to 4,000 PSI',
            'Descaling and grease removal for long‑term flow',
            'Pre/post camera inspection to validate results',
            'Suitable for residential and commercial lines',
            'Maintenance plans available'
        ],
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '7',
        sImg:'/images/service/7.jpg',
        sIcon:'/images/icon/sink.png',
        slug:'slab-leak-repair',
        sTitle: 'Slab Leak Repair',
        description:'Expert detection and repair to protect your foundation and home.',
        overview: 'Slab leaks require precision and care. We locate the leak, discuss repair paths — direct access or reroute — and restore service while protecting your home’s structure and finishes.',
        keyPoints: [
            'Pressure testing and isolation to find leak',
            'Direct repair or reroute options clearly explained',
            'Experienced crews to minimize dust and noise',
            'Drywall patching and clean site practices',
            'Permits and code compliance handled'
        ],
        ssImg1:'/images/service-single/1.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '8',
        sImg:'/images/service/4.jpg',
        sIcon:'/images/icon/pipe.png',
        slug:'accessible-clean-out',
        sTitle: 'Accessible Clean Out',
        description:'Install or upgrade accessible clean outs for easier maintenance.',
        overview: 'Proper cleanouts make future maintenance faster and less invasive. We install new cleanouts or relocate existing ones to accessible locations, ensuring code compliance and easier service access.',
        keyPoints: [
            'Evaluate best location for accessibility',
            'Install new cleanout to code',
            'Optional backwater valve recommendations',
            'Labeling and cap protection included',
            'Improves future service time and cost'
        ],
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    // {
    //     Id: '6',
    //     sImg:'/images/service/6.jpg',
    //     sIcon:'/images/icon/remodeling.png',
    //     slug:'Remodeling-Service',
    //     sTitle: 'Remodeling Service',
    //     description:'Electronic typesetting rema essentially unchanged was popularised.',
    //     ssImg1:'/images/service-single/2.jpg',
    //     ssImg2:'/images/service-single/3.jpg',
    // },
   
]
export default Services;