const Services = [
    // {
    //     Id: '1',
    //     sImg:'/images/service/1.jpg',
    //     sIcon:'/images/icon/kitchen-utensils.png',
    //     slug:'Kitchen-Plumbing',
    //     sTitle: 'Kitchen Plumbing',
    //     description:'Electronic typesetting rema essentially unchanged was popularised.',
    //     ssImg1:'/images/service-single/2.jpg',
    //     ssImg2:'/images/service-single/3.jpg',
    // },
    // {
    //     Id: '2',
    //     sImg:'/images/service/2.jpg',
    //     sIcon:'/images/icon/gas-stove.png',
    //     slug:'Gas-Line-Services',
    //     sTitle: 'Gas Line Services',
    //     description:'Electronic typesetting rema essentially unchanged was popularised.',
    //     ssImg1:'/images/service-single/2.jpg',
    //     ssImg2:'/images/service-single/3.jpg',
    // },
    // {
    //     Id: '3',
    //     sImg:'/images/service/3.jpg',
    //     sIcon:'/images/icon/water-tap.png',
    //     slug:'Water-Line-Repair',
    //     sTitle: 'Water Line Repair',
    //     description:'Electronic typesetting rema essentially unchanged was popularised.',
    //     ssImg1:'/images/service-single/2.jpg',
    //     ssImg2:'/images/service-single/3.jpg',
    // },

    {
        Id: '1',
        sImg:'https://source.unsplash.com/1600x900/?plumbing,emergency',
        sIcon:'/images/icon/express-delivery.svg',
        slug:'emergency-plumbing',
        sTitle: 'Emergency Plumbing',
        description:'24/7 rapid plumbing rescue—leaks stopped, backups cleared, burst pipes fixed now.',
        overview: 'Minutes matter when plumbing fails. Our live dispatch connects you to a licensed plumber right away — day or night. We stop active leaks, stabilize the problem, and give clear options with upfront pricing before any work begins.',
        keyPoints: [
            'Live 24/7 dispatch with same-day arrival',
            'On‑site diagnostics and immediate stabilization',
            'Upfront pricing with repair options explained',
            'Fully stocked trucks to solve most issues on the spot',
            'Clean, respectful work — we protect floors and surfaces'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?plumber,leak',
        ssImg2:'https://source.unsplash.com/1000x700/?plumbing,tools',
    },
    {
        Id: '2',
        sImg:'https://source.unsplash.com/1600x900/?plumbing,drain',
        sIcon:'/images/icon/water-tap.png',
        slug:'drain-cleaning',
        sTitle: 'Drain Cleaning — $69.99',
        description:'Clogs gone fast—flat‑rate clearing with clean, verified flow.',
        overview: 'Slow or backed‑up drains can become bigger problems. We clear the clog fast, verify proper flow, and advise maintenance to keep lines clean. For heavy buildup, we can camera‑inspect and hydro jet for a long‑term fix.',
        keyPoints: [
            'Flat‑rate residential drain clearing — no surprises',
            'Power augering to remove common clogs',
            'Optional camera inspection to locate trouble spots',
            'Hydro jetting available for grease and scale',
            'Warranty‑backed work and clean job sites'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?drain,plumber',
        ssImg2:'https://source.unsplash.com/1000x700/?pipe,cleaning',
    },
    {
        Id: '3',
        sImg:'https://source.unsplash.com/1600x900/?plumber,water-heater',
        sIcon:'/images/icon/water-tap.png',
        slug:'water-heater-service',
        sTitle: 'Water Heater Repair & Install',
        description:'Hot water restored today—expert repair or efficient tank/tankless install.',
        overview: 'No hot water? We repair and replace tank and tankless units from all major brands. We explain repair vs replace options, handle permits, and install to code with proper venting, gas, and recirculation where needed.',
        keyPoints: [
            'Same‑day repair and replacement for most models',
            'Tank and tankless expertise — gas and electric',
            'Code‑compliant installs with permits handled',
            'Removal and disposal of old units',
            'Manufacturer warranties honored and registered'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?water-heater,installation',
        ssImg2:'https://source.unsplash.com/1000x700/?plumbing,heater',
    },
    {
        Id: '4',
        sImg:'https://source.unsplash.com/1600x900/?plumbing,leak-detection',
        sIcon:'/images/icon/pipe.png',
        slug:'leak-detection-repair',
        sTitle: 'Leak Detection & Repair',
        description:'Find leaks fast—precise detection and clean, targeted repairs.',
        overview: 'Hidden leaks waste water and damage finishes. We use acoustic and thermal tools to pinpoint the source precisely, then repair with the least‑invasive method possible — protecting your home and preventing repeat issues.',
        keyPoints: [
            'Non‑invasive detection to pinpoint leak sources',
            'Targeted repairs that minimize wall/floor cuts',
            'Pressure testing to confirm repairs',
            'Slab leak specialists available',
            'Moisture mapping and cleanup recommendations'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?leak,detector',
        ssImg2:'https://source.unsplash.com/1000x700/?pipe,repair',
    },
    {
        Id: '5',
        sImg:'https://source.unsplash.com/1600x900/?sewer,trenchless',
        sIcon:'/images/icon/pipe.png',
        slug:'sewer-trenchless',
        sTitle: 'Sewer & Trenchless Solutions',
        description:'Restore sewer flow with trenchless tech—fix lines without tearing up your yard.',
        overview: 'For failing or root‑intruded sewer lines, trenchless methods restore flow without tearing up landscaping. We camera‑inspect, recommend the right approach — lining, pipe bursting, or spot repair — and verify results before we leave.',
        keyPoints: [
            'Camera inspection with recorded footage',
            'CIPP lining and pipe bursting options',
            'Minimal disruption to concrete and landscaping',
            'New cleanouts installed where needed',
            'Post‑repair verification and warranty'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?sewer,pipe',
        ssImg2:'https://source.unsplash.com/1000x700/?trenchless,plumbing',
    },
    {
        Id: '6',
        sImg:'https://source.unsplash.com/1600x900/?hydro,jetting',
        sIcon:'/images/icon/prototype.svg',
        slug:'hydro-jetting',
        sTitle: 'Hydro Jetting Service',
        description:'Deep‑clean pipes—high‑pressure jetting that blasts away grease, scale, roots.',
        overview: 'High‑pressure jetting scours the inside of pipes — ideal for grease, scale, and roots. Paired with camera inspection, it confirms a deep clean and helps prevent future clogs.',
        keyPoints: [
            'Commercial‑grade jetting up to 4,000 PSI',
            'Descaling and grease removal for long‑term flow',
            'Pre/post camera inspection to validate results',
            'Suitable for residential and commercial lines',
            'Maintenance plans available'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?jetting,sewer',
        ssImg2:'https://source.unsplash.com/1000x700/?pressure,water',
    },
    {
        Id: '7',
        sImg:'https://source.unsplash.com/1600x900/?slab,leak',
        sIcon:'/images/icon/sink.png',
        slug:'slab-leak-repair',
        sTitle: 'Slab Leak Repair',
        description:'Protect your foundation—precise slab leak detection and low‑impact repairs.',
        overview: 'Slab leaks require precision and care. We locate the leak, explain direct access vs reroute, and restore service with low‑impact repairs that protect structure and finishes.',
        keyPoints: [
            'Pressure testing and isolation to find leak',
            'Direct repair or reroute options clearly explained',
            'Experienced crews to minimize dust and noise',
            'Drywall patching and clean site practices',
            'Permits and code compliance handled'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?leak,foundation',
        ssImg2:'https://source.unsplash.com/1000x700/?plumber,repair',
    },
    {
        Id: '8',
        sImg:'https://source.unsplash.com/1600x900/?cleanout,plumbing',
        sIcon:'/images/icon/pipe.png',
        slug:'accessible-clean-out',
        sTitle: 'Accessible Clean Out',
        description:'Service made easier—install accessible cleanouts for faster maintenance.',
        overview: 'Proper cleanouts make maintenance faster and less invasive. We install new cleanouts or relocate existing ones to accessible locations, ensuring code compliance and easier service access.',
        keyPoints: [
            'Evaluate best location for accessibility',
            'Install new cleanout to code',
            'Optional backwater valve recommendations',
            'Labeling and cap protection included',
            'Improves future service time and cost'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?cleanout,pipe',
        ssImg2:'https://source.unsplash.com/1000x700/?maintenance,plumbing',
    },
    {
        Id: '9',
        sImg:'https://source.unsplash.com/1600x900/?burst,pipe',
        sIcon:'/images/icon/water-tap.png',
        slug:'burst-pipe-repair',
        sTitle: 'Burst Pipe Repair',
        description:'Stop damage fast—emergency burst pipe repairs and durable replacements.',
        overview: 'We locate the break fast, shut off water, and perform durable repairs or replacements. We protect your property during service and advise on prevention.',
        keyPoints: [
            'Rapid response and water shut‑off',
            'Targeted repair or section replacement',
            'Moisture mitigation recommendations',
            'Pressure testing to verify integrity',
            'Clean, respectful work inside homes'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?pipe,break',
        ssImg2:'https://source.unsplash.com/1000x700/?water,damage',
    },
    {
        Id: '10',
        sImg:'https://source.unsplash.com/1600x900/?toilet,repair',
        sIcon:'/images/icon/sink.png',
        slug:'toilet-repair-install',
        sTitle: 'Toilet Repair & Install',
        description:'Fix leaks and clogs—or upgrade with a clean, code‑perfect install.',
        overview: 'From running toilets to full replacements, we service all brands and install new units to code, including low‑flow and comfort‑height options.',
        keyPoints: [
            'Flapper, fill valve, and wax ring fixes',
            'Clog clearing and re‑seating',
            'New installs with haul‑away',
            'Seal testing to prevent future leaks',
            'ADA and water‑saving options'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?toilet,plumber',
        ssImg2:'https://source.unsplash.com/1000x700/?bathroom,install',
    },
    {
        Id: '11',
        sImg:'https://source.unsplash.com/1600x900/?faucet,repair',
        sIcon:'/images/icon/water-tap.png',
        slug:'faucet-repair-install',
        sTitle: 'Faucet Repair & Install',
        description:'End drips and low pressure—sleek replacements installed to spec.',
        overview: 'We repair leaks and pressure issues, and install new faucets for kitchens, baths, and laundry — neatly and to manufacturer specs.',
        keyPoints: [
            'Cartridge and aerator replacements',
            'Supply line and shut‑off valve updates',
            'Finish‑safe work to protect sinks and counters',
            'Kitchen, bath, and utility faucets',
            'Optional touch and pull‑down models'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?faucet,install',
        ssImg2:'https://source.unsplash.com/1000x700/?kitchen,sink',
    },
    {
        Id: '12',
        sImg:'https://source.unsplash.com/1600x900/?garbage,disposal',
        sIcon:'/images/icon/prototype.svg',
        slug:'garbage-disposal',
        sTitle: 'Garbage Disposal Service',
        description:'Quiet, reliable disposals—jam clearing, repairs, and new installs.',
        overview: 'We service all major disposal brands — clear jams and replace worn units. Installs include proper wiring checks and leak tests.',
        keyPoints: [
            'Jam clearing and reset diagnostics',
            'Noise and vibration fixes',
            'New installs with flange and putty set',
            'Electrical and leak safety checks',
            'Warranty options available'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?disposal,kitchen',
        ssImg2:'https://source.unsplash.com/1000x700/?sink,repair',
    },
    {
        Id: '13',
        sImg:'https://source.unsplash.com/1600x900/?repiping,plumbing',
        sIcon:'/images/icon/pipe.png',
        slug:'repiping',
        sTitle: 'Whole‑Home Repiping',
        description:'Reliable water flow—whole‑home repiping done cleanly and to code.',
        overview: 'Frequent leaks or poor pressure? Repiping restores reliability. We plan efficient routes, protect finishes, and complete work cleanly and to code.',
        keyPoints: [
            'Copper, PEX, and hybrid options',
            'Pressure balancing and isolation valves',
            'Drywall patching coordinated',
            'Permit handling and inspections',
            'Clear timelines and daily cleanup'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?pipe,installation',
        ssImg2:'https://source.unsplash.com/1000x700/?copper,pipe',
    },
    {
        Id: '14',
        sImg:'https://source.unsplash.com/1600x900/?water,line',
        sIcon:'/images/icon/water-tap.png',
        slug:'main-water-line',
        sTitle: 'Main Water Line Repair/Replace',
        description:'Strong, stable supply—repair or replace aging main lines.',
        overview: 'We locate and repair yard and street‑side line failures, and replace undersized or corroded service lines for strong, reliable flow.',
        keyPoints: [
            'Leak location and isolation',
            'Trenchless replacement options',
            'Pressure regulation via PRV setup',
            'Code‑compliant materials and depth',
            'Final pressure and flow testing'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?main,water',
        ssImg2:'https://source.unsplash.com/1000x700/?yard,plumbing',
    },
    {
        Id: '15',
        sImg:'https://source.unsplash.com/1600x900/?sewer,line',
        sIcon:'/images/icon/pipe.png',
        slug:'sewer-line-repair',
        sTitle: 'Sewer Line Repair & Replace',
        description:'Clear diagnostics, lasting fixes—camera‑guided sewer repairs & replacements.',
        overview: 'We diagnose root intrusion and breaks with camera inspections, then perform spot repairs or full replacements — using trenchless techniques where possible.',
        keyPoints: [
            'Recorded camera inspections',
            'Spot repair or full replacement',
            'CIPP lining and pipe bursting',
            'Cleanouts and backwater valves',
            'Warranty‑backed solutions'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?sewer,repair',
        ssImg2:'https://source.unsplash.com/1000x700/?pipe,burst',
    },
    {
        Id: '16',
        sImg:'https://source.unsplash.com/1600x900/?sewer,camera',
        sIcon:'/images/icon/prototype.svg',
        slug:'camera-inspection',
        sTitle: 'Camera Inspection',
        description:'See inside your pipes—HD video mapping to pinpoint problems.',
        overview: 'We map your drain and sewer lines to locate problems and provide clear recommendations, with video evidence for insurance or future reference.',
        keyPoints: [
            'HD footage and location mapping',
            'Pre/post service validation',
            'Ideal with jetting and sewer repairs',
            'Digital reports available',
            'Helps avoid repeat issues'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?camera,inspection',
        ssImg2:'https://source.unsplash.com/1000x700/?plumbing,inspection',
    },
    {
        Id: '17',
        sImg:'https://source.unsplash.com/1600x900/?backflow,prevention',
        sIcon:'/images/icon/water-tap.png',
        slug:'backflow-prevention',
        sTitle: 'Backflow Prevention & Testing',
        description:'Protect your water supply—certified backflow installs, repairs, and testing.',
        overview: 'Protect potable water with certified installation, repair, and annual testing of backflow prevention assemblies for residential and commercial systems.',
        keyPoints: [
            'Certified testing and documentation',
            'Repairs on all major devices',
            'New installs to code',
            'Irrigation and commercial systems',
            'Annual reminders available'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?backflow,device',
        ssImg2:'https://source.unsplash.com/1000x700/?testing,plumbing',
    },
    {
        Id: '18',
        sImg:'https://source.unsplash.com/1600x900/?water,softener',
        sIcon:'/images/icon/water-tap.png',
        slug:'water-softener',
        sTitle: 'Water Softener Install',
        description:'Softer water, less scale—right‑sized softener installs that protect plumbing.',
        overview: 'We size and install softeners to reduce scale, protect plumbing, and improve feel — including whole‑home systems with proper bypass and drain setups.',
        keyPoints: [
            'System sizing and placement',
            'Bypass valve and drain connections',
            'Media selection and setup',
            'Code‑compliant installs',
            'Maintenance guidance'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?softener,installation',
        ssImg2:'https://source.unsplash.com/1000x700/?appliance,water',
    },
    {
        Id: '19',
        sImg:'https://source.unsplash.com/1600x900/?reverse,osmosis',
        sIcon:'/images/icon/water-tap.png',
        slug:'reverse-osmosis',
        sTitle: 'Reverse Osmosis (RO) Systems',
        description:'Crisp, clean drinking water—under‑sink RO installed the right way.',
        overview: 'We install and maintain RO systems for great‑tasting water — with dedicated faucet, proper tank placement, and leak checks.',
        keyPoints: [
            'System selection and install',
            'Dedicated faucet setup',
            'Filter changes and maintenance',
            'Leak and pressure checks',
            'Options for fridge line connection'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?ro,system',
        ssImg2:'https://source.unsplash.com/1000x700/?drinking,water',
    },
    {
        Id: '20',
        sImg:'https://source.unsplash.com/1600x900/?water,filtration',
        sIcon:'/images/icon/water-tap.png',
        slug:'whole-home-filtration',
        sTitle: 'Whole‑Home Filtration',
        description:'Cleaner water everywhere—whole‑home filtration tailored to your quality.',
        overview: 'We design and install point‑of‑entry filtration tailored to local water quality — with media changes and service plans available.',
        keyPoints: [
            'Water quality assessment',
            'System sizing and plumbing',
            'Media selection and changes',
            'Bypass and drain setups',
            'Service and maintenance plans'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?filtration,system',
        ssImg2:'https://source.unsplash.com/1000x700/?whole,home',
    },
    {
        Id: '21',
        sImg:'https://source.unsplash.com/1600x900/?sump,pump',
        sIcon:'/images/icon/prototype.svg',
        slug:'sump-pump',
        sTitle: 'Sump Pump Install & Repair',
        description:'Keep basements and crawl spaces dry and protected.',
        overview: 'We install and service sump and ejector pumps — basins, check valves, and battery backups — for reliable performance.',
        keyPoints: [
            'Pump sizing and basin install',
            'Check valve and discharge piping',
            'Battery backup options',
            'Maintenance and testing',
            'Emergency replacements'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?basement,pump',
        ssImg2:'https://source.unsplash.com/1000x700/?crawlspace,dry',
    },
    {
        Id: '22',
        sImg:'https://source.unsplash.com/1600x900/?gas,line',
        sIcon:'/images/icon/gas-stove.png',
        slug:'gas-line-service',
        sTitle: 'Gas Line Repair & Install',
        description:'Safe gas piping for appliances and outdoor kitchens.',
        overview: 'Certified gas line service for appliances and outdoor projects — leak repair, new connections, and fire pit lines — tested and permitted.',
        keyPoints: [
            'Leak detection and repair',
            'New appliance hookups',
            'Outdoor kitchen/fire pit lines',
            'Pressure testing and permits',
            'Code‑compliant materials'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?gas,installation',
        ssImg2:'https://source.unsplash.com/1000x700/?outdoor,kitchen',
    },
    {
        Id: '23',
        sImg:'https://source.unsplash.com/1600x900/?pressure,regulator',
        sIcon:'/images/icon/sink.png',
        slug:'pressure-regulator-prv',
        sTitle: 'Pressure Regulator (PRV) Replace',
        description:'Protect lines and fixtures with proper water pressure.',
        overview: 'We test and replace failing PRVs to stabilize household water pressure — extending the life of appliances and plumbing fixtures.',
        keyPoints: [
            'Pressure testing at fixtures',
            'Code‑compliant PRV installs',
            'Shut‑off valve checks',
            'Leak and performance testing',
            'Warranty on parts and labor'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?prv,plumbing',
        ssImg2:'https://source.unsplash.com/1000x700/?pressure,valve',
    },
    {
        Id: '24',
        sImg:'https://source.unsplash.com/1600x900/?valve,replacement',
        sIcon:'/images/icon/water-tap.png',
        slug:'valve-replacement',
        sTitle: 'Valve Replacement',
        description:'Update failing shut‑offs and fixture valves.',
        overview: 'We replace stuck or leaking valves to improve safety and serviceability — including main shut‑offs and fixture stops.',
        keyPoints: [
            'Fixture stop and angle stop updates',
            'Main shut‑off replacements',
            'Supply line refreshes',
            'Leak checks across fixtures',
            'Neat, finish‑safe work'
        ],
        ssImg1:'https://source.unsplash.com/1000x700/?valve,repair',
        ssImg2:'https://source.unsplash.com/1000x700/?fixture,plumbing',
    },
    // {
    //     Id: '6',
    //     sImg:'/images/service/6.jpg',
    //     sIcon:'/images/icon/remodeling.png',
    //     slug:'Remodeling-Service',
    //     sTitle: 'Remodeling Service',
    //     description:'Electronic typesetting rema essentially unchanged was popularised.',
    //     ssImg1:'/images/service-single/2.jpg',
    //     ssImg2:'/images/service-single/3.jpg',
    // },
   
]
export default Services;
